version: "3"

services:
  mariadb:
    image: mariadb
    volumes:
      - mariadb-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  bench:
    build: .
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: on-failure
    volumes:
      - ./sites/frappe.localhost:/opt/frappe-bench/sites/frappe.localhost
      # - ./community:/opt/frappe-bench/apps/community
    environment:
      # add space separated APPs to install. Make sure they are added as volumes
      # - FRAPPE_APPS=community
volumes:
  mariadb-storage: {}
